Area_Name: state
Year: year
Subgroup: subgroup
Rape_Cases_Reported: rape_cases_reported
Victims_Above_50_Yrs: victims_above_50_yrs
Victims_Between_10-14_Yrs: victims_between_10_14_yrs
Victims_Between_14-18_Yrs: victims_between_14_18_yrs
Victims_Between_18-30_Yrs: victims_between_18_30_yrs
Victims_Between_30-50_Yrs: victims_between_30_50_yrs
Victims_of_Rape_Total: victims_of_rape_total
Victims_Upto_10_Yrs: victims_upto_10_yrs